//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Scripts/Control API/InputControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputControls"",
    ""maps"": [
        {
            ""name"": ""Touchsreen"",
            ""id"": ""ce283fff-2127-4183-9f39-aedb20576c08"",
            ""actions"": [
                {
                    ""name"": ""Touch Position"",
                    ""type"": ""Value"",
                    ""id"": ""f91283af-4c33-4260-ad8a-2df2ad5793ef"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Touch"",
                    ""type"": ""Button"",
                    ""id"": ""8b86a55f-465e-4415-b3c5-4e3a42629c87"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""7f094a5b-d570-458e-8316-2c1dfd5208fb"",
                    ""path"": ""<Touchscreen>/primaryTouch/press"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Touch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c95f2ef4-cccf-4cb1-a67e-4d2fcad0975a"",
                    ""path"": ""<Touchscreen>/primaryTouch/startPosition"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Touch Position"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Touchsreen
        m_Touchsreen = asset.FindActionMap("Touchsreen", throwIfNotFound: true);
        m_Touchsreen_TouchPosition = m_Touchsreen.FindAction("Touch Position", throwIfNotFound: true);
        m_Touchsreen_Touch = m_Touchsreen.FindAction("Touch", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Touchsreen
    private readonly InputActionMap m_Touchsreen;
    private ITouchsreenActions m_TouchsreenActionsCallbackInterface;
    private readonly InputAction m_Touchsreen_TouchPosition;
    private readonly InputAction m_Touchsreen_Touch;
    public struct TouchsreenActions
    {
        private @InputControls m_Wrapper;
        public TouchsreenActions(@InputControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @TouchPosition => m_Wrapper.m_Touchsreen_TouchPosition;
        public InputAction @Touch => m_Wrapper.m_Touchsreen_Touch;
        public InputActionMap Get() { return m_Wrapper.m_Touchsreen; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TouchsreenActions set) { return set.Get(); }
        public void SetCallbacks(ITouchsreenActions instance)
        {
            if (m_Wrapper.m_TouchsreenActionsCallbackInterface != null)
            {
                @TouchPosition.started -= m_Wrapper.m_TouchsreenActionsCallbackInterface.OnTouchPosition;
                @TouchPosition.performed -= m_Wrapper.m_TouchsreenActionsCallbackInterface.OnTouchPosition;
                @TouchPosition.canceled -= m_Wrapper.m_TouchsreenActionsCallbackInterface.OnTouchPosition;
                @Touch.started -= m_Wrapper.m_TouchsreenActionsCallbackInterface.OnTouch;
                @Touch.performed -= m_Wrapper.m_TouchsreenActionsCallbackInterface.OnTouch;
                @Touch.canceled -= m_Wrapper.m_TouchsreenActionsCallbackInterface.OnTouch;
            }
            m_Wrapper.m_TouchsreenActionsCallbackInterface = instance;
            if (instance != null)
            {
                @TouchPosition.started += instance.OnTouchPosition;
                @TouchPosition.performed += instance.OnTouchPosition;
                @TouchPosition.canceled += instance.OnTouchPosition;
                @Touch.started += instance.OnTouch;
                @Touch.performed += instance.OnTouch;
                @Touch.canceled += instance.OnTouch;
            }
        }
    }
    public TouchsreenActions @Touchsreen => new TouchsreenActions(this);
    public interface ITouchsreenActions
    {
        void OnTouchPosition(InputAction.CallbackContext context);
        void OnTouch(InputAction.CallbackContext context);
    }
}
